name: Build windows binaries

on:
  push:

jobs:     
  
  build-windows:

    runs-on: windows-2019

    steps:
    - name: Set up Cygwin
      uses: egor-tensin/setup-cygwin@v3
      with:
        platform: x64
        packages: cmake gcc-core gcc-g++ libusb1.0-devel libusb1.0 zip
    - name: Clone
      run: |
        git clone --depth=1 https://github.com/raspberrypi/usbboot 
    - name: Build
      run: |
        cd usbboot
        sed -i 's/$(CC)/gcc/' .\Makefile
        make
    - name: Create installer
      run: |
        choco install nsis
        cd usbboot
        cp -r "C:\Program Files (x86)\NSIS" .
        NSIS/makensis /v2 win32/install_script.nsi
    - name: zip windows artifact
      run: |
        dir
        zip -r rpiboot-windows usbboot/rpiboot usbboot/msd usbboot/Readme.md usbboot/license usbboot/win32
    - name: upload windows artifact
      uses: actions/upload-artifact@v2
      with:
        name: uploads
        path: rpiboot-windows.zip